### PR TITLE
Fix NPE after catching a Client/Service exception

### LINKED ISSUE #132: Fix NPE after catching Service/Client exception in DynamoDB
- [x] [reads](https://github.com/Netflix/ndbench/blob/master/ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java#L163)
- [x] [writes](https://github.com/Netflix/ndbench/blob/master/ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java#L190)

### PR DESCRIPTION
**Pull request by amcp**
Fixes #132

### CODE REVIEW

File: ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java [hunk 1]
```diff
@@ -153,12 +153,14 @@ public String readSingle(String key) throws Exception {
                 .withConsistentRead(config.consistentRead());
             item = table.getItem(spec);
             if (item == null) {
-                return null;
+            return null;
             }
         } catch (AmazonServiceException ase) {
             amazonServiceException(ase);
```
Comment (vinaykumarchella) [inline ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java]: NdBench plugin ideally should throw an exception when there an error processing operation, if the plugin swallows the exception there is no way for NdBench driver to know the failed operation, hence in the catch block, we should be re-throwing the exception rather than returning error message

**Comment by amcp** [comment]
@vinaykumarchella ProvisionedThroughputExceededException is a subclass of AmazonServiceException. When the workload is skewed (for example, the workload uses two keys and both keys are mapped to the same partition of a table with more than one partition), users will see this exception. Therefore, ProvisionedThroughputExceededException is not an error nor is an exceptional situation. For other exceptions, yes, we should interpret and re-throw the exception, but given [ProvisionedThroughputExceededException's background](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html), I think we should count them instead of rethrowing them.
Also, InternalServerErrorException is a subclass of AmazonServiceException. As noted in the [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html), "You may encounter Internal Server Errors while working with items. These are expected during the lifetime of a table. Any failed requests can be retried immediately." Therefore, I think we should count InternalServerErrorExceptions and not re-throw them.

**Comment by vinaykumarchella** [comment]
I agreed, these metrics are available in CloudWatch, but NdBench would be missing the metrics on those failures and/ or latencies. NdBench is supposed to have a unified view of client-side metrics regardless of the plugin/ server implementation. E.g., some server-side components/ servers might not be capturing P99th metric, which NdBench does. so we cant let NdBench users roam around for gathering metrics based on server implementation details and we want to provide a single and consistent view across the plugins regardless of its server component implementation details.  Hope this helps.
